version: '3.8'

services:
  quickwiki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_NAME: quickwiki
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11.5
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: quickwiki
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -ppassword
      interval: 1s
      timeout: 10s
      retries: 60
    
  adminer:
    image: adminer:4.8.1
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb